### ISSUE TITLE
Create: restructure_for_cmip6.py script

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-mip-tools#2]
# REQUIREMENT FOR SCRIPT

**NAME: restructure_for_cmip6.py**

**FUNCTION:**

Move files found under directory/directories into CMIP6-compliant directory structure ready for publication.

**INPUTS:**

```
-d --directory <base_output_directory>
-v --version <version_identifier> [default: v<YYYYMMDD> as TODAY]
-o --output <output_file_path> [default: $PWD/versioned_dirs.txt]
-h --help 
d1 [d2 ... dn]
```

Where `d1` to `dn` are individual directories to search for ".nc" files within.

**OUTPUTS:**

A list of output ESGF-compatible versioned directories written to `<output_file_path>`.

Print to terminal: 
 - `<N>` versioned directories created.
 - Written to: `<output_file_path>`.

**DETAILS:**

Move data to `<directory>` in DRS structure.

**EXAMPLE:**

 Inputs:
`  -d /gws/nopw/j04/cmip6_prep_vol3/cdds-test/AerChemMIP-astephen2/cdds_data/CMIP6/AerChemMIP/UKESM1-0-LL/piClim-control/r1i1p1f2/round-1/output/ap4`
  
 Outputs:
`  $PWD/versioned_dirs.txt`
  
**EXAMPLE FILES:**

Input:
`/gws/nopw/j04/cmip6_prep_vol3/cdds-test/AerChemMIP-astephen2/cdds_data/CMIP6/AerChemMIP/UKESM1-0-LL/piClim-control/r1i1p1f2/round-1/output/ap4/AERmon/mmrss/mmrss_AERmon_UKESM1-0-LL_piClim-control_r1i1p1f2_gn_185001-189412.nc`

Output:
`${directory}/CMIP6/AerChemMIP/MOHC/UKESM1-0-LL/piClim-control/r1i1p1f2/AERmon/mmrss/gn/v20191001`

**Comment by alaniwi** [comment]
Questions:

1. I do not see why we create output path in the archive.  This will be determined by using esgdrs as part of CREPP.  Do we not need output paths still on the GWS, but under a complete DRS structure?

In your example above, at least one facet (MOHC) is not present in either the existing directory path or in the filename.  This will therefore require looking in the file contents to extract that facet value.  If so, then it sounds like it might be easier to make use of esgdrs rather than .

but with an output directory on the GWS rather than the archive.  However, it would be a case of wrapping esgdrs

**Comment by alaniwi** [comment]
Questions:

1) I do not see why we create output path in the archive. This will be determined by using esgdrs as part of CREPP. Do we not need output paths still on the GWS, but under a complete DRS structure. 
 Please can you confirm.

>> We do **not** create anything in the archive with this script. The new structure is entirely created within the existing GWS where the data arrives from. The user runs the script and it (1) creates a directory structure (that will match the archive) and (2) moves the files into place within that directory structure. 

2) Is it your intention that in the generic case, the input path does not contain all the facet information?  This seems to be the case in your example above, where at least one facet (MOHC) is not present in either the existing directory path or in the filename.  But please can you confirm, because this would imply extracting information from the netCDF attributes.  In particular, please can you confirm whether *any* facet information should be extracted from the input directory path -- in which case, please specify the format of the directory path -- or whether it is entirely arbitrary and all the facet information should be extracted from the netCDF attributes.

>> The input path **does not** contain all facet information, so we need to retrieve that from a combination of the filename and/or the global attributes within each netCDF file. I suggest the best approach is to: 
  i. ignore all directory info
  ii. collect the facets from the file name
  iii. collect all facets from the global attributes within the file
  iv. validate that (ii) and (iii) match - if they don't then raise an Exception

>> The implication of the above is that all files should be processed before any are moved. I.e. you should only restructure the file/directory structure if you are happy that all files can be moved safely. 

Commenting now on the implementation (although dependent on your answer to question 2 regarding the spec), if information is to be extracted from netCDF attributes, it is *possible* that it is easiest to wrap esgdrs.  However, esgdrs will do a variety of things that are unwanted in this context, namely check for other existing versions under the output root and create the structure of directories and symlinks _under_ the (unversioned) dataset directory.  This could perhaps be circumvented by running esgdrs in "todo" (dry run) mode using a dummy (i.e. empty) output root, capturing the output, parsing output relating to what esgdrs would put under "files" and ignoring bits about where esgdrs would create symlinks, and presenting this with things suitably mapped.  But it might be easier just to ignore esgdrs at this stage and just inspect the netCDF attributes, using a hard-coded list of facets rather than looking in a publisher ini file as esgdrs does.

>> I will leave it to you to decide if `esgdrs` should be involved in this script.

**Comment by alaniwi** [comment]
Deployed now. Closing.
