### ISSUE TITLE
Unable to run `restructure-for-cmip6` on JASMIN

### ISSUE THREAD

**Issue by jonnyhtw** [cedadev/ceda-mip-tools#4]
Kia ora - Hi there

I'm trying to run the `restructure-for-cmip6` script on the `jasmin-cylc` virtual machine on JASMIN.

My example data which I want to run this script on is here...

`/gws/nopw/j04/aerchemmip_vol1/data/u-bi639/cdds`

I have created a new directory for the restructured data to go to here..

`/gws/nopw/j04/aerchemmip_vol1/data/u-bi639/esgf`

This is the full error message I get when I try to run `restructure-for-cmip6` in `/gws/nopw/j04/aerchemmip_vol1/data/u-bi639/esgf`...

```
> pwd
/gws/nopw/j04/aerchemmip_vol1/data/u-bi639/esgf

> restructure-for-cmip6 -d . /gws/nopw/j04/aerchemmip_vol1/data/u-bi639/cdds/
Traceback (most recent call last):
  File "/apps/contrib/ceda_mip_tools/v1.2/bin/restructure-for-cmip6", line 11, in <module>
    load_entry_point('ceda-mip-tools==1.2', 'console_scripts', 'restructure-for-cmip6')()
  File "/apps/contrib/ceda_mip_tools/v1.2/lib/python3.7/site-packages/ceda_mip_tools-1.2-py3.7.egg/ceda_mip_tools/restructure_for_cmip6/restructure_for_cmip6.py", line 206, in main
    rs.run()
  File "/apps/contrib/ceda_mip_tools/v1.2/lib/python3.7/site-packages/ceda_mip_tools-1.2-py3.7.egg/ceda_mip_tools/restructure_for_cmip6/restructure_for_cmip6.py", line 175, in run
    dataset_dirs, paths_to_dataset_dirs = self._get_dataset_dirs(paths)
  File "/apps/contrib/ceda_mip_tools/v1.2/lib/python3.7/site-packages/ceda_mip_tools-1.2-py3.7.egg/ceda_mip_tools/restructure_for_cmip6/restructure_for_cmip6.py", line 153, in _get_dataset_dirs
    for path in paths))
  File "/apps/contrib/ceda_mip_tools/v1.2/lib/python3.7/site-packages/ceda_mip_tools-1.2-py3.7.egg/ceda_mip_tools/restructure_for_cmip6/restructure_for_cmip6.py", line 153, in <genexpr>
    for path in paths))
  File "/apps/contrib/ceda_mip_tools/v1.2/lib/python3.7/site-packages/ceda_mip_tools-1.2-py3.7.egg/ceda_mip_tools/restructure_for_cmip6/dataset_id_getter.py", line 36, in get_dataset_id
    facets = self._get_facets(path)
  File "/apps/contrib/ceda_mip_tools/v1.2/lib/python3.7/site-packages/ceda_mip_tools-1.2-py3.7.egg/ceda_mip_tools/restructure_for_cmip6/dataset_id_getter.py", line 100, in _get_facets
    .format(path, key, val, val2))
ceda_mip_tools.restructure_for_cmip6.dataset_id_getter.DatasetIDGetterException: for file /gws/nopw/j04/aerchemmip_vol1/data/u-bi639/cdds/cdds_data/CMIP6/AerChemMIP/UKESM1-0-LL/piClim-HC/r1i1p1f2/round-1-monthly/output/ap4_concat/AERmon/emibvoc/emibvoc_AERmon_UKESM1-0-LL_piClim-HC_r1i1p1f2_gnOokmg341980.nc mismatch of grid_label from file contents (gn) and from pathname (gnOokmg341980)
```

I imagine I'm just using the wrong syntax?

Ngā mihi nui - Thanks a lot

Jonny Williams
NIWA, Aotearoa New Zealand

**Comment by alaniwi** [comment]
Hi, thanks for the query.

From the point of view of the software development I am going to close this as "won't fix" because I believe that the error is correct behaviour - though am happy to give advice either here or via the CEDA helpdesk.  (Nonetheless, the way that it reports the error could be improved, and I'll create a ticket for that.)

It seems that you have a bunch of input files with unusual filenames, as can be seen if you run the following in your `cdds` directory:
```
find . -type f -name '*.nc' \( -not -name '*_gn_*' -and -not -name '*_gnz_*' -and -not -name '*_gm_*' \)
```

The one given in the error message (last line of the output which you pasted above), namely
```
emibvoc_AERmon_UKESM1-0-LL_piClim-HC_r1i1p1f2_gnOokmg341980.nc
```
is an example of these.  It no longer seems to exist at time of writing, but taking another similar example file (called `emibvoc_AERmon_UKESM1-0-LL_piClim-HC_r1i1p1f2_gnkgThYt374512.nc`), it has correctly:
```
                :grid_label = "gn" ;
```
and in the case of another couple of other example files with similar names, they appear not to be usable files at present (`ncdump -h <filename>` gives `HDF5 error`).

For CMIP6, the filenames should adhere to the following format:

https://github.com/ESGF/config/blob/a79f2bc788ed799f720b857463a5eb6a6c374279/publisher-configs/ini/esg.cmip6.ini#L33
(which you may need to view in "raw" mode due to the long line)

Although the `restructure-for-cmip6` will ignore the directory names for the input file (its job is to move them to appropriately named output directories), it will not attempt to rename the files themselves.  It will, however, test that any facet values that appear both in the filename and in the netCDF attributes are consistent with each other.  Currently, if it finds a discrepancy then it will report an error, and I suspect that this is for the better in this case, because these filenames suggest that they are some kind of temporary files, as does the other behaviour described above.

If despite this you have a use case for an option for the script to rename the file if it finds such a discrepancy, rather than report an error, then please create a separate issue for this, and I will treat it as a feature request. But it would need to be used cautiously, because there is a slight danger in that case that if it is the netCDF attribute that is invalid, then this would be copied to the filename rather than rejecting the data. The error would then only get picked up at a later stage during the ingestion pipeline, where a controlled vocabulary check is performed.

**Comment by jonnyhtw** [comment]
Hi Alan

Thanks a lot for that. 

My guess at the moment is that those files are indeed temporary in nature and may get removed by the quality control step which hasn’t been run yet. 

Can you confirm that this is the right syntax though?...

```
> /gws/nopw/j04/aerchemmip_vol1/data/u-bi639/esgf

> restructure-for-cmip6 -d . /gws/nopw/j04/aerchemmip_vol1/data/u-bi639/cdds
```

All the best and thanks again

Jonny

**Comment by alaniwi** [comment]
Jonny,

Yes that looks fine, assuming that the directory which you mentioned first is where you have `cd`-ed into.  The output path is on the same filesystem as the input, but not overlapping with it, so that's perfect.  (In fact, `-d .` is the default.)

Regards,
Alan

**Comment by jonnyhtw** [comment]
Fab thanks. I'm having to rerun my CDDS analysis now so I'll test this ASAP.

All the best

Jonny

**Comment by jonnyhtw** [comment]
Woop this is working now! 🎉 

Thanks for your help!

Jonny
